/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'redouane' at '2/19/16 12:01 PM' with Gradle 2.6
 *
 * @author redouane, @date 2/19/16 12:01 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
